// <auto-generated />
using System;
using DE_Store_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DE_Store_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240831183740_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("DE_Store_Backend.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LoyaltyCard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomerId");

                    b.HasIndex("StoreId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerName = "Skye Johnson",
                            LoyaltyCard = false,
                            StoreId = 1
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerName = "Matthew Smith",
                            LoyaltyCard = true,
                            StoreId = 1
                        },
                        new
                        {
                            CustomerId = 3,
                            CustomerName = "Olivia Brown",
                            LoyaltyCard = false,
                            StoreId = 1
                        },
                        new
                        {
                            CustomerId = 4,
                            CustomerName = "Liam Johnson",
                            LoyaltyCard = true,
                            StoreId = 2
                        },
                        new
                        {
                            CustomerId = 5,
                            CustomerName = "Ava Williams",
                            LoyaltyCard = true,
                            StoreId = 2
                        },
                        new
                        {
                            CustomerId = 6,
                            CustomerName = "Noah Miller",
                            LoyaltyCard = false,
                            StoreId = 3
                        },
                        new
                        {
                            CustomerId = 7,
                            CustomerName = "Emma Davis",
                            LoyaltyCard = false,
                            StoreId = 3
                        },
                        new
                        {
                            CustomerId = 8,
                            CustomerName = "Sophia Wilson",
                            LoyaltyCard = true,
                            StoreId = 4
                        },
                        new
                        {
                            CustomerId = 9,
                            CustomerName = "James Anderson",
                            LoyaltyCard = true,
                            StoreId = 4
                        },
                        new
                        {
                            CustomerId = 10,
                            CustomerName = "Isabella Thomas",
                            LoyaltyCard = false,
                            StoreId = 4
                        },
                        new
                        {
                            CustomerId = 11,
                            CustomerName = "Mason Moore",
                            LoyaltyCard = true,
                            StoreId = 5
                        },
                        new
                        {
                            CustomerId = 12,
                            CustomerName = "Ethan Taylor",
                            LoyaltyCard = false,
                            StoreId = 5
                        },
                        new
                        {
                            CustomerId = 13,
                            CustomerName = "Mia Jackson",
                            LoyaltyCard = true,
                            StoreId = 5
                        },
                        new
                        {
                            CustomerId = 14,
                            CustomerName = "Charlotte Harris",
                            LoyaltyCard = true,
                            StoreId = 1
                        },
                        new
                        {
                            CustomerId = 15,
                            CustomerName = "Henry Clark",
                            LoyaltyCard = false,
                            StoreId = 2
                        },
                        new
                        {
                            CustomerId = 16,
                            CustomerName = "Alexander Lewis",
                            LoyaltyCard = true,
                            StoreId = 3
                        },
                        new
                        {
                            CustomerId = 17,
                            CustomerName = "Amelia King",
                            LoyaltyCard = false,
                            StoreId = 4
                        },
                        new
                        {
                            CustomerId = 18,
                            CustomerName = "Daniel Scott",
                            LoyaltyCard = true,
                            StoreId = 5
                        },
                        new
                        {
                            CustomerId = 19,
                            CustomerName = "Lucas Young",
                            LoyaltyCard = false,
                            StoreId = 1
                        },
                        new
                        {
                            CustomerId = 20,
                            CustomerName = "Zoe Turner",
                            LoyaltyCard = true,
                            StoreId = 2
                        },
                        new
                        {
                            CustomerId = 21,
                            CustomerName = "Ella Roberts",
                            LoyaltyCard = false,
                            StoreId = 1
                        },
                        new
                        {
                            CustomerId = 22,
                            CustomerName = "William Carter",
                            LoyaltyCard = true,
                            StoreId = 2
                        },
                        new
                        {
                            CustomerId = 23,
                            CustomerName = "Avery Martin",
                            LoyaltyCard = false,
                            StoreId = 3
                        },
                        new
                        {
                            CustomerId = 24,
                            CustomerName = "Logan Walker",
                            LoyaltyCard = true,
                            StoreId = 4
                        },
                        new
                        {
                            CustomerId = 25,
                            CustomerName = "Grace Hill",
                            LoyaltyCard = true,
                            StoreId = 5
                        },
                        new
                        {
                            CustomerId = 26,
                            CustomerName = "Lily Green",
                            LoyaltyCard = false,
                            StoreId = 1
                        },
                        new
                        {
                            CustomerId = 27,
                            CustomerName = "Hannah Adams",
                            LoyaltyCard = true,
                            StoreId = 2
                        },
                        new
                        {
                            CustomerId = 28,
                            CustomerName = "Jack Nelson",
                            LoyaltyCard = false,
                            StoreId = 3
                        },
                        new
                        {
                            CustomerId = 29,
                            CustomerName = "Victoria Baker",
                            LoyaltyCard = true,
                            StoreId = 4
                        },
                        new
                        {
                            CustomerId = 30,
                            CustomerName = "Leo Perez",
                            LoyaltyCard = true,
                            StoreId = 5
                        },
                        new
                        {
                            CustomerId = 31,
                            CustomerName = "Isabella Rivera",
                            LoyaltyCard = false,
                            StoreId = 1
                        },
                        new
                        {
                            CustomerId = 32,
                            CustomerName = "David Brooks",
                            LoyaltyCard = true,
                            StoreId = 2
                        },
                        new
                        {
                            CustomerId = 33,
                            CustomerName = "Mason Long",
                            LoyaltyCard = false,
                            StoreId = 3
                        },
                        new
                        {
                            CustomerId = 34,
                            CustomerName = "Samantha Hughes",
                            LoyaltyCard = true,
                            StoreId = 4
                        },
                        new
                        {
                            CustomerId = 35,
                            CustomerName = "Gabriel Murphy",
                            LoyaltyCard = false,
                            StoreId = 5
                        },
                        new
                        {
                            CustomerId = 36,
                            CustomerName = "Abigail Simmons",
                            LoyaltyCard = true,
                            StoreId = 1
                        },
                        new
                        {
                            CustomerId = 37,
                            CustomerName = "Harper Foster",
                            LoyaltyCard = false,
                            StoreId = 2
                        },
                        new
                        {
                            CustomerId = 38,
                            CustomerName = "Oliver Gonzales",
                            LoyaltyCard = true,
                            StoreId = 3
                        },
                        new
                        {
                            CustomerId = 39,
                            CustomerName = "Zoey Bryant",
                            LoyaltyCard = false,
                            StoreId = 4
                        },
                        new
                        {
                            CustomerId = 40,
                            CustomerName = "Scarlett Barnes",
                            LoyaltyCard = true,
                            StoreId = 5
                        });
                });

            modelBuilder.Entity("DE_Store_Backend.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountType = "Buy one get one free"
                        },
                        new
                        {
                            Id = 2,
                            DiscountType = "3 for 2"
                        },
                        new
                        {
                            Id = 3,
                            DiscountType = "None"
                        },
                        new
                        {
                            Id = 4,
                            DiscountType = "10% off"
                        },
                        new
                        {
                            Id = 5,
                            DiscountType = "Clearance"
                        });
                });

            modelBuilder.Entity("DE_Store_Backend.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            DiscountId = 3,
                            ProductDescription = "Fresh egg",
                            ProductName = "Egg",
                            ProductPrice = 12,
                            Stock = 100,
                            StoreId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            DiscountId = 4,
                            ProductDescription = "Chocolate egg",
                            ProductName = "Easter Egg",
                            ProductPrice = 20,
                            Stock = 50,
                            StoreId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            DiscountId = 1,
                            ProductDescription = "Luxury egg with gold leaf",
                            ProductName = "Golden Egg",
                            ProductPrice = 50,
                            Stock = 10,
                            StoreId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            DiscountId = 2,
                            ProductDescription = "Organic, free-range egg",
                            ProductName = "Organic Egg",
                            ProductPrice = 15,
                            Stock = 75,
                            StoreId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            DiscountId = 3,
                            ProductDescription = "Carton of 12 eggs",
                            ProductName = "Egg Carton",
                            ProductPrice = 120,
                            Stock = 30,
                            StoreId = 2
                        },
                        new
                        {
                            ProductId = 6,
                            DiscountId = 5,
                            ProductDescription = "Decorative painted egg",
                            ProductName = "Painted Egg",
                            ProductPrice = 30,
                            Stock = 25,
                            StoreId = 3
                        },
                        new
                        {
                            ProductId = 7,
                            DiscountId = 3,
                            ProductDescription = "Small and delicate",
                            ProductName = "Quail Egg",
                            ProductPrice = 25,
                            Stock = 200,
                            StoreId = 4
                        },
                        new
                        {
                            ProductId = 8,
                            DiscountId = 2,
                            ProductDescription = "Rich and creamy",
                            ProductName = "Duck Egg",
                            ProductPrice = 18,
                            Stock = 60,
                            StoreId = 4
                        },
                        new
                        {
                            ProductId = 9,
                            DiscountId = 4,
                            ProductDescription = "Large and exotic",
                            ProductName = "Ostrich Egg",
                            ProductPrice = 150,
                            Stock = 5,
                            StoreId = 5
                        },
                        new
                        {
                            ProductId = 10,
                            DiscountId = 1,
                            ProductDescription = "Luxurious and rare",
                            ProductName = "Caviar Egg",
                            ProductPrice = 300,
                            Stock = 8,
                            StoreId = 5
                        },
                        new
                        {
                            ProductId = 11,
                            DiscountId = 5,
                            ProductDescription = "Preserved delicacy",
                            ProductName = "Century Egg",
                            ProductPrice = 45,
                            Stock = 40,
                            StoreId = 3
                        },
                        new
                        {
                            ProductId = 12,
                            DiscountId = 3,
                            ProductDescription = "Exotic delicacy",
                            ProductName = "Balut",
                            ProductPrice = 35,
                            Stock = 70,
                            StoreId = 2
                        },
                        new
                        {
                            ProductId = 13,
                            DiscountId = 4,
                            ProductDescription = "Festive beverage",
                            ProductName = "Egg Nog",
                            ProductPrice = 60,
                            Stock = 90,
                            StoreId = 1
                        },
                        new
                        {
                            ProductId = 14,
                            DiscountId = 2,
                            ProductDescription = "Health supplement",
                            ProductName = "Egg White Protein",
                            ProductPrice = 80,
                            Stock = 120,
                            StoreId = 5
                        },
                        new
                        {
                            ProductId = 15,
                            DiscountId = 4,
                            ProductDescription = "Spicy egg treat",
                            ProductName = "Deviled Egg",
                            ProductPrice = 25,
                            Stock = 55,
                            StoreId = 1
                        },
                        new
                        {
                            ProductId = 16,
                            DiscountId = 3,
                            ProductDescription = "Classic egg salad",
                            ProductName = "Egg Salad",
                            ProductPrice = 50,
                            Stock = 85,
                            StoreId = 2
                        },
                        new
                        {
                            ProductId = 17,
                            DiscountId = 5,
                            ProductDescription = "Egg wrapped in sausage",
                            ProductName = "Scotch Egg",
                            ProductPrice = 40,
                            Stock = 35,
                            StoreId = 3
                        },
                        new
                        {
                            ProductId = 18,
                            DiscountId = 2,
                            ProductDescription = "Sweet egg pastry",
                            ProductName = "Egg Tart",
                            ProductPrice = 30,
                            Stock = 100,
                            StoreId = 4
                        },
                        new
                        {
                            ProductId = 19,
                            DiscountId = 1,
                            ProductDescription = "Preserved salty egg",
                            ProductName = "Salted Egg",
                            ProductPrice = 20,
                            Stock = 45,
                            StoreId = 5
                        },
                        new
                        {
                            ProductId = 20,
                            DiscountId = 3,
                            ProductDescription = "Pre chiken soup",
                            ProductName = "Egg Drop Soup",
                            ProductPrice = 35,
                            Stock = 110,
                            StoreId = 4
                        },
                        new
                        {
                            ProductId = 21,
                            DiscountId = 4,
                            ProductDescription = "Seasonal eggnog flavored latte",
                            ProductName = "Eggnog Latte",
                            ProductPrice = 45,
                            Stock = 95,
                            StoreId = 1
                        },
                        new
                        {
                            ProductId = 22,
                            DiscountId = 2,
                            ProductDescription = "Crispy egg rolls with filling",
                            ProductName = "Egg Rolls",
                            ProductPrice = 30,
                            Stock = 130,
                            StoreId = 2
                        },
                        new
                        {
                            ProductId = 23,
                            DiscountId = 1,
                            ProductDescription = "Light and fluffy egg mousse",
                            ProductName = "Egg Mousse",
                            ProductPrice = 55,
                            Stock = 40,
                            StoreId = 3
                        },
                        new
                        {
                            ProductId = 24,
                            DiscountId = 3,
                            ProductDescription = "Creamy egg pudding",
                            ProductName = "Egg Pudding",
                            ProductPrice = 40,
                            Stock = 75,
                            StoreId = 4
                        },
                        new
                        {
                            ProductId = 25,
                            DiscountId = 5,
                            ProductDescription = "Egg sandwich on whole grain bread",
                            ProductName = "Egg Sandwich",
                            ProductPrice = 35,
                            Stock = 65,
                            StoreId = 5
                        },
                        new
                        {
                            ProductId = 26,
                            DiscountId = 2,
                            ProductDescription = "Tacos filled with scrambled eggs",
                            ProductName = "Egg Tacos",
                            ProductPrice = 60,
                            Stock = 50,
                            StoreId = 1
                        },
                        new
                        {
                            ProductId = 27,
                            DiscountId = 4,
                            ProductDescription = "Poached eggs on English muffin",
                            ProductName = "Egg Benedict",
                            ProductPrice = 70,
                            Stock = 20,
                            StoreId = 2
                        },
                        new
                        {
                            ProductId = 28,
                            DiscountId = 3,
                            ProductDescription = "Sweet and smooth egg custard",
                            ProductName = "Egg Custard",
                            ProductPrice = 50,
                            Stock = 55,
                            StoreId = 3
                        },
                        new
                        {
                            ProductId = 29,
                            DiscountId = 1,
                            ProductDescription = "Egg and cheese muffin",
                            ProductName = "Egg Muffin",
                            ProductPrice = 45,
                            Stock = 90,
                            StoreId = 4
                        },
                        new
                        {
                            ProductId = 30,
                            DiscountId = 5,
                            ProductDescription = "Traditional egg drop soup",
                            ProductName = "Egg Soup",
                            ProductPrice = 25,
                            Stock = 70,
                            StoreId = 5
                        });
                });

            modelBuilder.Entity("DE_Store_Backend.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PurchaseId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            PurchaseId = 1,
                            CustomerId = 1,
                            ProductId = 1,
                            PurchaseTime = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 2,
                            CustomerId = 2,
                            ProductId = 2,
                            PurchaseTime = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 3,
                            CustomerId = 3,
                            ProductId = 3,
                            PurchaseTime = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 4,
                            CustomerId = 4,
                            ProductId = 4,
                            PurchaseTime = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 2
                        },
                        new
                        {
                            PurchaseId = 5,
                            CustomerId = 5,
                            ProductId = 5,
                            PurchaseTime = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 2
                        },
                        new
                        {
                            PurchaseId = 6,
                            CustomerId = 6,
                            ProductId = 6,
                            PurchaseTime = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 3
                        },
                        new
                        {
                            PurchaseId = 7,
                            CustomerId = 7,
                            ProductId = 11,
                            PurchaseTime = new DateTime(2024, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 3
                        },
                        new
                        {
                            PurchaseId = 8,
                            CustomerId = 8,
                            ProductId = 7,
                            PurchaseTime = new DateTime(2024, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 9,
                            CustomerId = 9,
                            ProductId = 8,
                            PurchaseTime = new DateTime(2024, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 10,
                            CustomerId = 10,
                            ProductId = 9,
                            PurchaseTime = new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 11,
                            CustomerId = 11,
                            ProductId = 10,
                            PurchaseTime = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5
                        },
                        new
                        {
                            PurchaseId = 12,
                            CustomerId = 12,
                            ProductId = 14,
                            PurchaseTime = new DateTime(2024, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5
                        },
                        new
                        {
                            PurchaseId = 13,
                            CustomerId = 13,
                            ProductId = 12,
                            PurchaseTime = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5
                        },
                        new
                        {
                            PurchaseId = 14,
                            CustomerId = 1,
                            ProductId = 13,
                            PurchaseTime = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 15,
                            CustomerId = 2,
                            ProductId = 4,
                            PurchaseTime = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 2
                        },
                        new
                        {
                            PurchaseId = 16,
                            CustomerId = 3,
                            ProductId = 5,
                            PurchaseTime = new DateTime(2024, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 2
                        },
                        new
                        {
                            PurchaseId = 17,
                            CustomerId = 4,
                            ProductId = 6,
                            PurchaseTime = new DateTime(2024, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 3
                        },
                        new
                        {
                            PurchaseId = 18,
                            CustomerId = 5,
                            ProductId = 1,
                            PurchaseTime = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 19,
                            CustomerId = 6,
                            ProductId = 7,
                            PurchaseTime = new DateTime(2024, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 20,
                            CustomerId = 7,
                            ProductId = 8,
                            PurchaseTime = new DateTime(2024, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 21,
                            CustomerId = 8,
                            ProductId = 9,
                            PurchaseTime = new DateTime(2024, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 22,
                            CustomerId = 9,
                            ProductId = 10,
                            PurchaseTime = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5
                        },
                        new
                        {
                            PurchaseId = 23,
                            CustomerId = 10,
                            ProductId = 11,
                            PurchaseTime = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 3
                        },
                        new
                        {
                            PurchaseId = 24,
                            CustomerId = 11,
                            ProductId = 12,
                            PurchaseTime = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5
                        },
                        new
                        {
                            PurchaseId = 25,
                            CustomerId = 12,
                            ProductId = 13,
                            PurchaseTime = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 26,
                            CustomerId = 13,
                            ProductId = 14,
                            PurchaseTime = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5
                        },
                        new
                        {
                            PurchaseId = 27,
                            CustomerId = 14,
                            ProductId = 15,
                            PurchaseTime = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 28,
                            CustomerId = 15,
                            ProductId = 16,
                            PurchaseTime = new DateTime(2024, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 2
                        },
                        new
                        {
                            PurchaseId = 29,
                            CustomerId = 16,
                            ProductId = 17,
                            PurchaseTime = new DateTime(2024, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 3
                        },
                        new
                        {
                            PurchaseId = 30,
                            CustomerId = 17,
                            ProductId = 18,
                            PurchaseTime = new DateTime(2024, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 31,
                            CustomerId = 18,
                            ProductId = 19,
                            PurchaseTime = new DateTime(2024, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5
                        },
                        new
                        {
                            PurchaseId = 32,
                            CustomerId = 19,
                            ProductId = 20,
                            PurchaseTime = new DateTime(2024, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 33,
                            CustomerId = 20,
                            ProductId = 15,
                            PurchaseTime = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 34,
                            CustomerId = 21,
                            ProductId = 1,
                            PurchaseTime = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 35,
                            CustomerId = 22,
                            ProductId = 2,
                            PurchaseTime = new DateTime(2024, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 2
                        },
                        new
                        {
                            PurchaseId = 36,
                            CustomerId = 23,
                            ProductId = 3,
                            PurchaseTime = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 3
                        },
                        new
                        {
                            PurchaseId = 37,
                            CustomerId = 24,
                            ProductId = 4,
                            PurchaseTime = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 38,
                            CustomerId = 25,
                            ProductId = 5,
                            PurchaseTime = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5
                        },
                        new
                        {
                            PurchaseId = 39,
                            CustomerId = 26,
                            ProductId = 6,
                            PurchaseTime = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 40,
                            CustomerId = 27,
                            ProductId = 7,
                            PurchaseTime = new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 2
                        },
                        new
                        {
                            PurchaseId = 41,
                            CustomerId = 28,
                            ProductId = 8,
                            PurchaseTime = new DateTime(2024, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 3
                        },
                        new
                        {
                            PurchaseId = 42,
                            CustomerId = 29,
                            ProductId = 9,
                            PurchaseTime = new DateTime(2024, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 43,
                            CustomerId = 30,
                            ProductId = 10,
                            PurchaseTime = new DateTime(2024, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5
                        },
                        new
                        {
                            PurchaseId = 44,
                            CustomerId = 31,
                            ProductId = 11,
                            PurchaseTime = new DateTime(2024, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 45,
                            CustomerId = 32,
                            ProductId = 12,
                            PurchaseTime = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 2
                        },
                        new
                        {
                            PurchaseId = 46,
                            CustomerId = 33,
                            ProductId = 13,
                            PurchaseTime = new DateTime(2024, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 3
                        },
                        new
                        {
                            PurchaseId = 47,
                            CustomerId = 34,
                            ProductId = 14,
                            PurchaseTime = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 48,
                            CustomerId = 35,
                            ProductId = 15,
                            PurchaseTime = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5
                        },
                        new
                        {
                            PurchaseId = 49,
                            CustomerId = 36,
                            ProductId = 16,
                            PurchaseTime = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 50,
                            CustomerId = 37,
                            ProductId = 17,
                            PurchaseTime = new DateTime(2024, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 2
                        },
                        new
                        {
                            PurchaseId = 51,
                            CustomerId = 38,
                            ProductId = 18,
                            PurchaseTime = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 3
                        },
                        new
                        {
                            PurchaseId = 52,
                            CustomerId = 39,
                            ProductId = 19,
                            PurchaseTime = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 53,
                            CustomerId = 40,
                            ProductId = 20,
                            PurchaseTime = new DateTime(2024, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5
                        },
                        new
                        {
                            PurchaseId = 54,
                            CustomerId = 21,
                            ProductId = 21,
                            PurchaseTime = new DateTime(2024, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 55,
                            CustomerId = 22,
                            ProductId = 22,
                            PurchaseTime = new DateTime(2024, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 2
                        },
                        new
                        {
                            PurchaseId = 56,
                            CustomerId = 23,
                            ProductId = 23,
                            PurchaseTime = new DateTime(2024, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 3
                        },
                        new
                        {
                            PurchaseId = 57,
                            CustomerId = 24,
                            ProductId = 24,
                            PurchaseTime = new DateTime(2024, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 58,
                            CustomerId = 25,
                            ProductId = 25,
                            PurchaseTime = new DateTime(2024, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5
                        },
                        new
                        {
                            PurchaseId = 59,
                            CustomerId = 26,
                            ProductId = 26,
                            PurchaseTime = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 60,
                            CustomerId = 27,
                            ProductId = 27,
                            PurchaseTime = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 2
                        },
                        new
                        {
                            PurchaseId = 61,
                            CustomerId = 28,
                            ProductId = 28,
                            PurchaseTime = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 3
                        },
                        new
                        {
                            PurchaseId = 62,
                            CustomerId = 29,
                            ProductId = 29,
                            PurchaseTime = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 63,
                            CustomerId = 30,
                            ProductId = 30,
                            PurchaseTime = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5
                        },
                        new
                        {
                            PurchaseId = 64,
                            CustomerId = 31,
                            ProductId = 21,
                            PurchaseTime = new DateTime(2024, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 65,
                            CustomerId = 32,
                            ProductId = 22,
                            PurchaseTime = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 2
                        },
                        new
                        {
                            PurchaseId = 66,
                            CustomerId = 33,
                            ProductId = 23,
                            PurchaseTime = new DateTime(2024, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 3
                        },
                        new
                        {
                            PurchaseId = 67,
                            CustomerId = 34,
                            ProductId = 24,
                            PurchaseTime = new DateTime(2024, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 68,
                            CustomerId = 35,
                            ProductId = 25,
                            PurchaseTime = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5
                        },
                        new
                        {
                            PurchaseId = 69,
                            CustomerId = 36,
                            ProductId = 26,
                            PurchaseTime = new DateTime(2024, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 70,
                            CustomerId = 37,
                            ProductId = 27,
                            PurchaseTime = new DateTime(2024, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 2
                        },
                        new
                        {
                            PurchaseId = 71,
                            CustomerId = 38,
                            ProductId = 28,
                            PurchaseTime = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 3
                        },
                        new
                        {
                            PurchaseId = 72,
                            CustomerId = 39,
                            ProductId = 29,
                            PurchaseTime = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 73,
                            CustomerId = 40,
                            ProductId = 30,
                            PurchaseTime = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5
                        },
                        new
                        {
                            PurchaseId = 74,
                            CustomerId = 21,
                            ProductId = 22,
                            PurchaseTime = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 2
                        },
                        new
                        {
                            PurchaseId = 75,
                            CustomerId = 22,
                            ProductId = 23,
                            PurchaseTime = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 3
                        },
                        new
                        {
                            PurchaseId = 76,
                            CustomerId = 23,
                            ProductId = 24,
                            PurchaseTime = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4
                        },
                        new
                        {
                            PurchaseId = 77,
                            CustomerId = 24,
                            ProductId = 25,
                            PurchaseTime = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5
                        },
                        new
                        {
                            PurchaseId = 78,
                            CustomerId = 25,
                            ProductId = 26,
                            PurchaseTime = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1
                        },
                        new
                        {
                            PurchaseId = 79,
                            CustomerId = 26,
                            ProductId = 27,
                            PurchaseTime = new DateTime(2024, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 2
                        },
                        new
                        {
                            PurchaseId = 80,
                            CustomerId = 27,
                            ProductId = 28,
                            PurchaseTime = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 3
                        });
                });

            modelBuilder.Entity("DE_Store_Backend.Models.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StoreId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            StoreId = 1,
                            StoreName = "Egg Factory"
                        },
                        new
                        {
                            StoreId = 2,
                            StoreName = "Egg Factory Backup"
                        },
                        new
                        {
                            StoreId = 3,
                            StoreName = "Egg Factory Outlet"
                        },
                        new
                        {
                            StoreId = 4,
                            StoreName = "Downtown Egg Mart"
                        },
                        new
                        {
                            StoreId = 5,
                            StoreName = "Suburban Egg Depot"
                        });
                });

            modelBuilder.Entity("DE_Store_Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("userRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Skye",
                            LastName = "Jack",
                            PasswordHash = "a60aaf3786de4d0b745b27a8aad0f0b602fbeedbdf7e7881c7f865813808d70a",
                            StoreId = 1,
                            Username = "Skye1357",
                            userRole = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Matthew",
                            LastName = "Jack",
                            PasswordHash = "a60aaf3786de4d0b745b27a8aad0f0b602fbeedbdf7e7881c7f865813808d70a",
                            StoreId = 2,
                            Username = "Mtjack1",
                            userRole = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "a60aaf3786de4d0b745b27a8aad0f0b602fbeedbdf7e7881c7f865813808d70a",
                            StoreId = 3,
                            Username = "JD123",
                            userRole = "Employee"
                        });
                });

            modelBuilder.Entity("DE_Store_Backend.Models.Customer", b =>
                {
                    b.HasOne("DE_Store_Backend.Models.Store", "Store")
                        .WithMany("Customers")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("DE_Store_Backend.Models.Product", b =>
                {
                    b.HasOne("DE_Store_Backend.Models.Discount", "Discount")
                        .WithMany()
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DE_Store_Backend.Models.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("DE_Store_Backend.Models.Purchase", b =>
                {
                    b.HasOne("DE_Store_Backend.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DE_Store_Backend.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DE_Store_Backend.Models.Store", "Store")
                        .WithMany("Purchases")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("DE_Store_Backend.Models.User", b =>
                {
                    b.HasOne("DE_Store_Backend.Models.Store", "Store")
                        .WithMany("Users")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("DE_Store_Backend.Models.Store", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Products");

                    b.Navigation("Purchases");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
